# Generated by Django 3.1.2 on 2020-11-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=12)),
                ('player_black_nickname', models.CharField(max_length=50)),
                ('player_white_nickname', models.CharField(max_length=50)),
                ('board_size', models.IntegerField()),
                ('preset', models.CharField(max_length=30)),
                ('kifu', models.TextField()),
            ],
        ),
    ]
