# Generated by Django 3.1.2 on 2020-11-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_black_nickname',
            new_name='player_black',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_white_nickname',
            new_name='player_white',
        ),
    ]
