# Generated by Django 3.1.2 on 2020-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goban', '0002_auto_20201104_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='kifu',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
