# Generated by Django 3.1.2 on 2020-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goban', '0002_auto_20201101_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='handicap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='board_size',
            field=models.IntegerField(default=0),
        ),
    ]
