# Generated by Django 3.1.2 on 2021-02-04 21:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('player_black', models.CharField(max_length=50)),
                ('player_white', models.CharField(max_length=50)),
                ('room_visitors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, null=True, size=None)),
                ('board_size', models.IntegerField(default=0)),
                ('handicap', models.IntegerField(default=0)),
                ('preset', models.CharField(max_length=30)),
                ('kifu', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, null=True, size=None)),
            ],
        ),
    ]
