# Generated by Django 3.1.2 on 2020-11-13 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goban', '0003_auto_20201108_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='kifu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='room_visitors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, null=True, size=None),
        ),
    ]
